### ISSUE TITLE
The wired label extraction in TensorFlow model

### ISSUE THREAD

**Issue by nagachika** [sachinruk/doc2vec_tf#1]
Hi.
I'm very appreciate your notebook because I have to implement Doc2Vec in TensorFlow.
I came to the 2nd chunk of `TensorFlow Model` in test_doc2vec.ipynb, I think extracting label for every instance (piece of words with length skip_window*2) after deleting centered word is wrong. Isn't it?

```
k = 0
for doc_id, sentence  in enumerate(data):
    for i in range(skip_window, len(sentence)-skip_window):
        buffer = sentence[i-skip_window:i+skip_window+1]
        del buffer[skip_window]
        labels[k] = sentence[i]
        context[k] = buffer
        doc[k] = doc_id
        k += 1
```

I mean `labels[k] = sentence[i]` should be placed before `del buffer[skip_window]`.
I'm sorry If this is misunderstandings.

**Comment by sachinruk** [comment]
You raise a really good point! I did a little bit of an experiment as follows:
```
In [3]: a = list(range(10))

In [4]: a
Out[4]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [5]: b = a[0:5]

In [6]: b
Out[6]: [0, 1, 2, 3, 4]

In [7]: del b[2]

In [8]: b
Out[8]: [0, 1, 3, 4]

In [9]: a
Out[9]: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
```
As you can see a is unaffected by the `del b[2]` operation. However, just to be on the safe side I will change it to as you suggested. Its hard to know when python passes things by reference or by value.

Also my code is still experimental. I'm not entirely convinced that this is what doc2vec is supposed to be doing. More to follow!

**Comment by nagachika** [comment]
Oh I'm sorry for bother you. I miss understood the label was extracted from buffer variable...
Thank you for taking your time and kind explanation!

**Comment by sachinruk** [comment]
Not at all. I appreciate you taking the time. Let me know if you spot any other potential mistakes. Cheers.
